# Google Cloud Build configuration for Social SoloBoss Automation
steps:
  # Build shared package
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    dir: '.'

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build', '--workspace=packages/shared']
    dir: '.'

  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/social-soloboss-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/social-soloboss-backend:latest'
      - '-f'
      - 'packages/backend/Dockerfile.prod'
      - '.'

  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/social-soloboss-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/social-soloboss-frontend:latest'
      - '-f'
      - 'packages/frontend/Dockerfile.prod'
      - '.'

  # Push backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/social-soloboss-backend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/social-soloboss-backend:latest']

  # Push frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/social-soloboss-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/social-soloboss-frontend:latest']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'social-soloboss-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/social-soloboss-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3001'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'social-soloboss-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/social-soloboss-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'