export const ERROR_CODES = {
  // Authentication Errors
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  
  // Rate Limit Errors
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RATE_LIMIT_TEMPORARY: 'RATE_LIMIT_TEMPORARY',
  
  // Content Errors
  CONTENT_INVALID_FORMAT: 'CONTENT_INVALID_FORMAT',
  CONTENT_TOO_LONG: 'CONTENT_TOO_LONG',
  CONTENT_POLICY_VIOLATION: 'CONTENT_POLICY_VIOLATION',
  CONTENT_MISSING_REQUIRED: 'CONTENT_MISSING_REQUIRED',
  
  // Network Errors
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_CONNECTION_FAILED: 'NETWORK_CONNECTION_FAILED',
  NETWORK_DNS_ERROR: 'NETWORK_DNS_ERROR',
  
  // Platform Errors
  PLATFORM_SERVICE_UNAVAILABLE: 'PLATFORM_SERVICE_UNAVAILABLE',
  PLATFORM_MAINTENANCE: 'PLATFORM_MAINTENANCE',
  PLATFORM_API_ERROR: 'PLATFORM_API_ERROR',
  PLATFORM_NOT_SUPPORTED: 'PLATFORM_NOT_SUPPORTED',
  
  // Post Errors
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_ALREADY_PUBLISHED: 'POST_ALREADY_PUBLISHED',
  POST_SCHEDULING_FAILED: 'POST_SCHEDULING_FAILED',
  POST_EXECUTION_FAILED: 'POST_EXECUTION_FAILED',
  
  // Integration Errors
  INTEGRATION_CONNECTION_FAILED: 'INTEGRATION_CONNECTION_FAILED',
  INTEGRATION_WEBHOOK_FAILED: 'INTEGRATION_WEBHOOK_FAILED',
  INTEGRATION_DATA_INVALID: 'INTEGRATION_DATA_INVALID',
  
  // Validation Errors
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_OUT_OF_RANGE: 'VALIDATION_OUT_OF_RANGE',
  
  // System Errors
  SYSTEM_DATABASE_ERROR: 'SYSTEM_DATABASE_ERROR',
  SYSTEM_QUEUE_ERROR: 'SYSTEM_QUEUE_ERROR',
  SYSTEM_STORAGE_ERROR: 'SYSTEM_STORAGE_ERROR',
  SYSTEM_ENCRYPTION_ERROR: 'SYSTEM_ENCRYPTION_ERROR'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

export interface ErrorResponse {
  code: ErrorCode;
  message: string;
  details?: Record<string, any>;
  retryable: boolean;
  retryAfter?: number;
}

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Authentication token has expired',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Authentication token is invalid',
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions for this operation',
  [ERROR_CODES.AUTH_USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid login credentials',
  
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'API rate limit exceeded',
  [ERROR_CODES.RATE_LIMIT_TEMPORARY]: 'Temporary rate limit in effect',
  
  [ERROR_CODES.CONTENT_INVALID_FORMAT]: 'Content format is invalid',
  [ERROR_CODES.CONTENT_TOO_LONG]: 'Content exceeds platform character limit',
  [ERROR_CODES.CONTENT_POLICY_VIOLATION]: 'Content violates platform policies',
  [ERROR_CODES.CONTENT_MISSING_REQUIRED]: 'Required content fields are missing',
  
  [ERROR_CODES.NETWORK_TIMEOUT]: 'Network request timed out',
  [ERROR_CODES.NETWORK_CONNECTION_FAILED]: 'Failed to connect to service',
  [ERROR_CODES.NETWORK_DNS_ERROR]: 'DNS resolution failed',
  
  [ERROR_CODES.PLATFORM_SERVICE_UNAVAILABLE]: 'Platform service is currently unavailable',
  [ERROR_CODES.PLATFORM_MAINTENANCE]: 'Platform is under maintenance',
  [ERROR_CODES.PLATFORM_API_ERROR]: 'Platform API returned an error',
  [ERROR_CODES.PLATFORM_NOT_SUPPORTED]: 'Platform is not supported',
  
  [ERROR_CODES.POST_NOT_FOUND]: 'Post not found',
  [ERROR_CODES.POST_ALREADY_PUBLISHED]: 'Post has already been published',
  [ERROR_CODES.POST_SCHEDULING_FAILED]: 'Failed to schedule post',
  [ERROR_CODES.POST_EXECUTION_FAILED]: 'Failed to execute scheduled post',
  
  [ERROR_CODES.INTEGRATION_CONNECTION_FAILED]: 'Failed to connect to integration service',
  [ERROR_CODES.INTEGRATION_WEBHOOK_FAILED]: 'Webhook processing failed',
  [ERROR_CODES.INTEGRATION_DATA_INVALID]: 'Integration data is invalid',
  
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 'Required field is missing',
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 'Field format is invalid',
  [ERROR_CODES.VALIDATION_OUT_OF_RANGE]: 'Field value is out of acceptable range',
  
  [ERROR_CODES.SYSTEM_DATABASE_ERROR]: 'Database operation failed',
  [ERROR_CODES.SYSTEM_QUEUE_ERROR]: 'Queue operation failed',
  [ERROR_CODES.SYSTEM_STORAGE_ERROR]: 'File storage operation failed',
  [ERROR_CODES.SYSTEM_ENCRYPTION_ERROR]: 'Encryption/decryption operation failed'
};

export const RETRYABLE_ERROR_CODES: ErrorCode[] = [
  ERROR_CODES.RATE_LIMIT_EXCEEDED,
  ERROR_CODES.RATE_LIMIT_TEMPORARY,
  ERROR_CODES.NETWORK_TIMEOUT,
  ERROR_CODES.NETWORK_CONNECTION_FAILED,
  ERROR_CODES.PLATFORM_SERVICE_UNAVAILABLE,
  ERROR_CODES.PLATFORM_MAINTENANCE,
  ERROR_CODES.SYSTEM_DATABASE_ERROR,
  ERROR_CODES.SYSTEM_QUEUE_ERROR,
  ERROR_CODES.SYSTEM_STORAGE_ERROR
];